### ISSUE TITLE
Sleep doesnt work.

### ISSUE THREAD

**Issue by tuxpowered** [gnodipac886/MatebookXPro-hackintosh#31] opened 2019-09-05 16:57 UTC
Not sure what to provide to help diagnosis, but when I put the matebook to sleep (either by shutting the lid, or by  Apple > Sleep the unit initially goes to sleep with in about 30 seconds, and then usually less then 30 seconds later comes back on line.

I can verify this by several factors, 
The Wifi dongle comes back on line (little green light)
The fans still spin
The battery is dead by the end of the day.

I have disabled the BT in the bios because it kept causing crashes. (when it woke from sleep-ish state it had a crash dialog that showed the BT being the cause)

I am using a tp-link AC600 Nano adapter. (Archer T2U Nano) designed and made for MacOS with the current drivers.

MacOS version 10.14.5

Any help is appreciated. Never really noticed how annoying it is to not have a laptop go to sleep until it doesn't.

**Comment by bn3t** [comment] 2019-10-08 16:21
Did you find a solution to this problem since then?

**Comment by gnodipac886** [comment] 2019-10-23 19:08
Its been something that's been bothering me too, I will look into this when I have more time on my hands, as of now I am going to update the repo with 10.15 and we'll see how that goes.

**Comment by Picroc** [comment] 2019-10-23 22:25
I have issues with sleep too. In report the reason for "Sleep transition timed out" is IOUSBHostFamily, sometimes Audio (when I do not close Spotify).

Sleep is almost every time working perfectly without consuming a single battery percent for the night when I unplug all cables from the notebook. Otherwise, it may not go to sleep at all.

**Comment by Picroc** [comment] 2019-10-25 15:13
> Do you also unplug the wifi dongle ? I use the advised Edimax N150.

No, I don't have one yet

**Comment by bn3t** [comment] 2019-11-22 20:54
Hey, I was wondering if you would have a solution to this problem now. Thanks for your help.

**Comment by edTheGuy00** [comment] 2019-11-26 16:30
Hey, I tried debugging this but all I could get from the kernel logs was `Wake reason: ?` which is completely useless lol. 

I reverted back to Darrens [CLOVER](https://github.com/Darrenpan20/Matebook-X-Pro-Hackintosh-latest-update.) and sleep works fine again.

**Comment by Talal916** [comment] 2019-11-27 00:12
@edTheGuy00 Let us know how it goes! Are you on Catalina?

**Comment by AshleyMiller9696** [comment] 2019-11-27 09:50
+ which file is that exactly?
or do we have to copy everything?

**Comment by bn3t** [comment] 2019-11-27 09:56
> Hey, I tried debugging this but all I could get from the kernel logs was `Wake reason: ?` which is completely useless lol.
> 
> I reverted back to Darrens [CLOVER](https://github.com/Darrenpan20/Matebook-X-Pro-Hackintosh-latest-update.) and sleep works fine again.
> 
> If I have time I'll try replacing bit-by-bit to see if I can narrow down what causes the issue.

This repo does not seem to be updated for Catalina. Are you on Catalina or Mojave?

**Comment by edTheGuy00** [comment] 2019-11-27 10:56
@bn3t Yes, I'm still in Mojave. I encountered the sleep issue before I was able to update.

**Comment by tabousaleh3** [comment] 2019-11-30 19:36
Enjoying my matebook with catalina but im in the same boat. Closed my lid and saw it go to sleep.  Noticed usb wifi lights flicker later and laptop is dry of any power less than a couple hours later (left it at around 40%).  Hoping theres a solution so I can actually depend on it! ill try taking out the wifi usb and seeing if it drains any slower

**Comment by willwaush** [comment] 2019-12-07 14:21
I'm running Catalina 10.15.1 and I do confirm the Sleep issue. Either closing the lid or by the system, it initially sleeps fine but after a few seconds it gets back on. I can tell it by the Wifi dongle green light and by the battery drain.

I hope someone finds a solution. I'm not very technical but if you guys need any report or help, I'm here.

**Comment by masenov** [comment] 2019-12-18 13:15
Removing kext/Other/USBInjectAll.kext did the trick for me (Catalina 15.2)

I am not an expert, but maybe @gnodipac886 can confirm that this does not break other functionality?

**Comment by willwaush** [comment] 2019-12-18 14:36
And do your USB ports still work fine? Have you tried also extending them with an hub maybe?

**Comment by masenov** [comment] 2019-12-18 14:42
> And do your USB ports still work fine? Have you tried also extending them with an hub maybe?

I tried a wifi dongle (edimax EW-7822ULC) from the usb port and usb stick through a usb type c port with the matebook adapter - and they both seem to work fine.

**Comment by orhan** [comment] 2019-12-19 09:15
I can confirm removing **kext/Other/USBInjectAll.kext** works. 🎉 

No wake-ups during the night, only around 2% of battery loss, woke up from sleep without any problems. 👍

**Comment by willwaush** [comment] 2019-12-19 11:36
Okay, I'm on Catalina 15.2. Removing USBInjectAll.kext makes sleep work flawlessly.

The issue now is that using any kind of Hub to expand the C-type ports doesn't make USB 3.0 work.
I have tried using Huawei's hub and.. HDMI works, USB-A too but just with USB 2.0 dongles.. it isn't able to read my USB 3.0 pen drive. 
Laptop's integrated USB- works withouth issues.

I guess we need a specific patched USBInjectAll kext which doesn't wake up all the ports randomly but just targets the needed ones (as far as I understand). There are some guides online but It's out of my ability to try so. 

I hope someone will help.

**Comment by Talal916** [comment] 2019-12-20 06:03
Can anyone confirm if the Logitech USB Unifying Receiver works when connected through a type c hub with this fix?

**Comment by gnodipac886** [comment] 2019-12-25 08:39
Issue should be solved with next update

**Closed by gnodipac886** 2019-12-25 08:39 UTC

**Comment by bn3t** [comment] 2019-12-26 10:53
Nice Christmas gift! Thanks
